branch-defaults:
  default:
    environment: equithon-website-staging
    group_suffix: null
global:
  application_name: equithon-website
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
